### PR TITLE
Add no-checksum to index

### PR DESCRIPTION
**Pull request by vagishagupta23**
Added `no-checksum` to the suricata-intel-index for the sources
which have MD5 files.

### CODE REVIEW

**Comment by jasonish** [comment]
@victorjulien Any thoughts on adding this to the index?

**Comment by jasonish** [comment]
Merged. Thanks Vagisha!

**Comment by victorjulien** [comment]
Is it too late to rename this to something like 'skip-checksum' or a plain 'checksum: {true|false}'? The double negation may make sense in the code, but user facing it's not as nice.

**Comment by jasonish** [comment]
Its in master, but its not published yet, so I think we can change it.

**Pull request closed without merging**
