### PR TITLE
ruleset: add ptrules open

### PR DESCRIPTION
**Pull request by cloffyn**
Add recently published ptrules open ruleset by PT. This ruleset is a successor for an old ptresearch/attackdetection that is obsolete.

### CODE REVIEW

**Comment by jasonish** [comment]
Looks OK here. Are you still sticking to the SID range of 10000000-11999999 as documented here: https://sidallocation.org/

**Comment by cloffyn** [comment]
Yes, we are still using this range. Our team plans to transfer some rules from the old repository. Should I add a "replace" referencing it? Or it's not necessary due to the presence of the "obsolete"?

**Comment by jasonish** [comment]
> Should I add a "replace" referencing it? Or it's not necessary due to the presence of the "obsolete"?

Not necessary in this case, `obsolete` will do.

**Comment by jasonish** [comment]
Merged. Thanks!

**Pull request merged**
