### PR TITLE
[add] MalSilo ip, dns and url rules sources

### PR DESCRIPTION
**Pull request by raw-data**
@jasonish as suggested in https://github.com/OISF/suricata-update/pull/231, changes have been pushed to this index repo.

### CODE REVIEW

**Comment by jasonish** [comment]
These 3 sources all seem related. Would it make more sense to bundle them in a tar.gz and just have a single source? Suricata-Update can then be used to disable part of them.

**Comment by raw-data** [comment]
Hi @jasonish, all sources are now bundled under a tar.gz file, a md5 checksum is also offered like et/open.

**Comment by jasonish** [comment]
2 things:
* Do you have an informational URL users can go to for more information on this ruleset? We don't have a field for this yet, but I'm thinking of adding one.
* There appears to be an error in one of the rules:
```
8/7/2020 -- 17:09:15 - <Error> -- [ERRCODE: SC_ERR_INVALID_SIGNATURE(39)] - error parsing signature "alert http any any -> $EXTERNAL_NET any (msg:"MalSilo MALWARE (remcos) Detected"; flow:established,to_server; content:""; http_host; depth:0; fast_pattern; content:"443//azu/ch/index.php"; nocase; depth:21; http_uri; metadata: reference: url,malsilo.gitlab.io/feeds/dumps/master-feed.json; classtype:trojan-activity; sid:5000464; rev:1; metadata: tag peexe32,tag pegui, created_at 2020_07_08, malware_family remcos, updated_at 2020_07_08;)" from file /var/lib/suricata/rules/suricata.rules at line 1031
```

**Comment by raw-data** [comment]
Hi @jasonish , thanks for the heads-up. I have two pages that describes the rules set, or more in general, which kind of threats MalSilo deals with.

- https://raw-data.gitlab.io/post/feeds/
- https://raw-data.gitlab.io/post/malsilo_2.1/

**Comment by raw-data** [comment]
Hi @jasonish , any chances to see this integrated into `master` ?

**Comment by jasonish** [comment]
Thanks. I merged this in after squashing the 2 commits, and I added one of those links above as a homepage in the index.

**Comment by raw-data** [comment]
Thank you @jasonish looks good! Just one note, may I suggested to use this page https://raw-data.gitlab.io/post/malsilo_2.1/ for the `homepage` value? It's dedicated to Suricata

**Comment by jasonish** [comment]
> Thank you @jasonish looks good! Just one note, may I suggested to use this page https://raw-data.gitlab.io/post/malsilo_2.1/ for the `homepage` value? It's dedicated to Suricata

Done. Thanks.

**Pull request closed without merging**
