### PR TITLE
rulesets: add more abuse.ch rulesets

### PR DESCRIPTION
**Pull request by jasonish**

### CODE REVIEW

**Comment by jufajardini** [comment]
Neat commit organization :)
One nit: I think there's a typo in this one? https://github.com/OISF/suricata-intel-index/pull/19/commits/5bcdeeb67ff6a8f78afd4b29473981121d78668f

**Comment by jasonish** [comment]
> Neat commit organization :) One nit: I think there's a typo in this one? [5bcdeeb](https://github.com/OISF/suricata-intel-index/commit/5bcdeeb67ff6a8f78afd4b29473981121d78668f)

`FingerprintRuleset`?

**Comment by jufajardini** [comment]
> [@jasonish ](/jasonish)
> ` [sslbl: deprecated in favor new of new abuse.ch namespace](/OISF/suricata-intel-index/pull/19/commits/5bcdeeb67ff6a8f78afd4b29473981121d78668f)`

the double new new, is that expected? "deprecated in favor new of new abuse.ch namespace"

**Comment by jasonish** [comment]
Typos fixed: https://github.com/OISF/suricata-intel-index/pull/20

**Pull request closed without merging**
